### ISSUE TITLE
Support talking to JIRA over HTTPS

### ISSUE THREAD

**Issue by bwbaugh** [bartfrenk/time-tracker#3]
Trying to connect to JIRA over HTTPS gives `HttpExceptionRequest` `TlsNotSupported`.

**Comment by bartfrenk** [comment]
Thanks! Marking this as a bug. It might take a while before I get to this.

**Comment by bartfrenk** [comment]
Fixed in https://github.com/bartfrenk/time-tracker/commit/bc40327448155c5ac169c8d83aff3035e48d6bb1
